// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0w4XopvSjF_83buAJGSN9BDz9tNYhjpY',
    appId: '1:640184459240:web:2158c1cc0573e007f18e5d',
    messagingSenderId: '640184459240',
    projectId: 'csc4360-activity17-fcm',
    authDomain: 'csc4360-activity17-fcm.firebaseapp.com',
    storageBucket: 'csc4360-activity17-fcm.firebasestorage.app',
    measurementId: 'G-YYC1FB248V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWvIznm6NaxJeL6eFGCyYjsxQF0hSHo3I',
    appId: '1:640184459240:android:fec440ca7f30db65f18e5d',
    messagingSenderId: '640184459240',
    projectId: 'csc4360-activity17-fcm',
    storageBucket: 'csc4360-activity17-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_9QRJP_z-VgOagIQkk974Ud-X6TqwMg',
    appId: '1:640184459240:ios:bc970dc0d54abb0cf18e5d',
    messagingSenderId: '640184459240',
    projectId: 'csc4360-activity17-fcm',
    storageBucket: 'csc4360-activity17-fcm.firebasestorage.app',
    iosBundleId: 'com.example.fcmdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_9QRJP_z-VgOagIQkk974Ud-X6TqwMg',
    appId: '1:640184459240:ios:bc970dc0d54abb0cf18e5d',
    messagingSenderId: '640184459240',
    projectId: 'csc4360-activity17-fcm',
    storageBucket: 'csc4360-activity17-fcm.firebasestorage.app',
    iosBundleId: 'com.example.fcmdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0w4XopvSjF_83buAJGSN9BDz9tNYhjpY',
    appId: '1:640184459240:web:96337f537b6806caf18e5d',
    messagingSenderId: '640184459240',
    projectId: 'csc4360-activity17-fcm',
    authDomain: 'csc4360-activity17-fcm.firebaseapp.com',
    storageBucket: 'csc4360-activity17-fcm.firebasestorage.app',
    measurementId: 'G-D4CJQ0M1R9',
  );
}
